language: node_js

node_js:
    - "8"
    - "10"
    - "11"

cache: yarn

script:
    - npm run lint
    - npm run build

jobs:
    include:
        - stage: Publish docs
          if: type = push AND fork = false AND tag IS blank
          script: scripts/travis/publishDocs.sh
